server:
  port: 8888

spring:
  application:
    name: ead-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tadeuespindolapalermo/ead-config-server-repo
          default-label: main
          username: tadeuespindolapalermo
          password: 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

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost